# Generated by Django 5.0.6 on 2024-06-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operacio",
            fields=[
                ("id_operacio", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
            ],
            options={
                "db_table": "operacio",
            },
        ),
        migrations.CreateModel(
            name="Ciutat",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ciutat",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "nif",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=20)),
                ("adreca", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "client",
            },
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "iban",
                    models.CharField(max_length=34, primary_key=True, serialize=False),
                ),
                ("data_obertura", models.DateField()),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=15)),
                ("entidad", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "compte",
            },
        ),
        migrations.CreateModel(
            name="Gestor",
            fields=[
                ("id_empleat", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("data_inici", models.DateField()),
            ],
            options={
                "db_table": "gestor",
            },
        ),
        migrations.CreateModel(
            name="CarrecComissions",
            fields=[
                (
                    "idOperacio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                ("import_comissio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Efectiu",
            fields=[
                (
                    "idOperacio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                ("quantitat", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "idOperacio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                (
                    "IBAN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.compte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "NIF",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.client",
                    ),
                ),
                ("facturacio", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="Particular",
            fields=[
                (
                    "NIF",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.client",
                    ),
                ),
                (
                    "ingressos_anuals",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OficinaCentral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_oficina", models.CharField(max_length=100)),
                ("empleats", models.IntegerField()),
                (
                    "nom_ciutat_fk",
                    models.ForeignKey(
                        db_column="nom_ciutat",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bancaCatalana.ciutat",
                    ),
                ),
            ],
            options={
                "db_table": "oficina_central",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("id_sucursal", models.AutoField(primary_key=True, serialize=False)),
                ("carrer", models.CharField(max_length=255)),
                (
                    "id_oficina",
                    models.ForeignKey(
                        db_column="id_oficina",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bancaCatalana.oficinacentral",
                    ),
                ),
                (
                    "nom_ciutat",
                    models.ForeignKey(
                        db_column="nom_ciutat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bancaCatalana.ciutat",
                    ),
                ),
            ],
            options={
                "db_table": "sucursal",
            },
        ),
        migrations.CreateModel(
            name="RelacioTransferencies",
            fields=[
                (
                    "idOperacio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.transferencia",
                    ),
                ),
                ("suma", models.IntegerField()),
                (
                    "IBAN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.compte",
                    ),
                ),
            ],
        ),
    ]
