# Generated by Django 5.0.6 on 2024-06-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operacio",
            fields=[
                ("id_operacio", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                ("importt", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "operacio",
            },
        ),
        migrations.CreateModel(
            name="Ciutat",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "ciutat",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "nif",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=20)),
                ("adreca", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "client",
            },
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "iban",
                    models.CharField(max_length=34, primary_key=True, serialize=False),
                ),
                ("data_obertura", models.DateField()),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=15)),
                ("entidad", models.CharField(max_length=100)),
                (
                    "nif",
                    models.ForeignKey(
                        db_column="nif",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.client",
                    ),
                ),
            ],
            options={
                "db_table": "compte",
            },
        ),
        migrations.CreateModel(
            name="Gestor",
            fields=[
                ("id_empleat", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("data_inici", models.DateField()),
            ],
            options={
                "db_table": "gestor",
            },
        ),
        migrations.CreateModel(
            name="CarrecComissions",
            fields=[
                (
                    "id_operacio",
                    models.OneToOneField(
                        db_column="id_operacio",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                ("import_real", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "carrec_comissions",
            },
        ),
        migrations.CreateModel(
            name="Efectiu",
            fields=[
                (
                    "id_operacio",
                    models.OneToOneField(
                        db_column="id_operacio",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                ("quantitat", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "efectiu",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "nif",
                    models.OneToOneField(
                        db_column="nif",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.client",
                    ),
                ),
                ("facturacio", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "empresa",
            },
        ),
        migrations.CreateModel(
            name="Particular",
            fields=[
                (
                    "nif",
                    models.OneToOneField(
                        db_column="nif",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.client",
                    ),
                ),
                (
                    "ingressos_anuals",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
            ],
            options={
                "db_table": "particular",
            },
        ),
        migrations.AddField(
            model_name="operacio",
            name="iban_origen",
            field=models.ForeignKey(
                db_column="IBAN_origen",
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.compte",
            ),
        ),
        migrations.CreateModel(
            name="OficinaCentral",
            fields=[
                (
                    "id_oficina",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("empleats", models.IntegerField()),
                (
                    "nom_ciutat",
                    models.ForeignKey(
                        db_column="nom_ciutat",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bancaCatalana.ciutat",
                    ),
                ),
            ],
            options={
                "db_table": "oficina_central",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("id_sucursal", models.AutoField(primary_key=True, serialize=False)),
                ("carrer", models.CharField(max_length=100)),
                (
                    "id_empleat",
                    models.OneToOneField(
                        db_column="id_empleat",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.gestor",
                    ),
                ),
                (
                    "id_oficina",
                    models.ForeignKey(
                        db_column="id_oficina",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.oficinacentral",
                    ),
                ),
                (
                    "nom_ciutat",
                    models.ForeignKey(
                        db_column="nom_ciutat",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.ciutat",
                    ),
                ),
            ],
            options={
                "db_table": "sucursal",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="id_sucursal",
            field=models.ForeignKey(
                db_column="id_sucursal",
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id_operacio",
                    models.OneToOneField(
                        db_column="id_operacio",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bancaCatalana.operacio",
                    ),
                ),
                ("import_real", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "IBAN_desti",
                    models.ForeignKey(
                        db_column="IBAN_desti",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bancaCatalana.compte",
                    ),
                ),
            ],
            options={
                "db_table": "transferencia",
            },
        ),
    ]
