# Generated by Django 5.0.6 on 2024-06-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oficinacentral",
            name="nom_ciutat",
            field=models.ForeignKey(
                db_column="nom_ciutat",
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.ciutat",
            ),
        ),
    ]
