# Generated by Django 5.0.6 on 2024-06-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operacio",
            name="iban_origen",
            field=models.ForeignKey(
                db_column="iban_origen",
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.compte",
            ),
        ),
    ]
