# Generated by Django 5.0.6 on 2024-06-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oficinacentral",
            old_name="nom_ciutat_fk",
            new_name="nom_ciutat",
        ),
        migrations.RemoveField(
            model_name="sucursal",
            name="nom_ciutat",
        ),
        migrations.AddField(
            model_name="sucursal",
            name="id_empleat",
            field=models.OneToOneField(
                db_column="id_empleat",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.gestor",
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="carrer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="id_oficina",
            field=models.ForeignKey(
                db_column="id_oficina",
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.oficinacentral",
            ),
        ),
    ]
