# Generated by Django 5.0.6 on 2024-06-10 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ciutat",
            table="practica.ciutat",
        ),
    ]
