# Generated by Django 5.0.6 on 2024-06-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bancaCatalana",
            "0002_rename_nom_ciutat_fk_oficinacentral_nom_ciutat_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sucursal",
            name="id_oficina",
            field=models.ForeignKey(
                db_column="id_oficina",
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                to="bancaCatalana.oficinacentral",
            ),
        ),
    ]
