# Generated by Django 5.0.6 on 2024-06-11 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0002_alter_ciutat_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ciutat",
            table="ciutat",
        ),
    ]
