# Generated by Django 5.0.6 on 2024-06-12 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bancaCatalana",
            "0003_oficinacentral_id_alter_oficinacentral_id_oficina_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gestor",
            table="gestor",
        ),
    ]
