# Generated by Django 5.0.6 on 2024-06-13 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0003_alter_sucursal_id_oficina"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empresa",
            old_name="NIF",
            new_name="nif",
        ),
        migrations.RenameField(
            model_name="particular",
            old_name="NIF",
            new_name="nif",
        ),
    ]
