# Generated by Django 5.0.6 on 2024-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0004_rename_nif_empresa_nif_rename_nif_particular_nif"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="particular",
            table="particular",
        ),
    ]
