# Generated by Django 5.0.6 on 2024-06-12 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0004_alter_gestor_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gestor",
            old_name="dataInici",
            new_name="data_inici",
        ),
        migrations.RenameField(
            model_name="gestor",
            old_name="idEmpleat",
            new_name="id_empleat",
        ),
    ]
