# Generated by Django 5.0.6 on 2024-06-12 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0005_rename_datainici_gestor_data_inici_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sucursal",
            old_name="nom",
            new_name="nom_ciutat",
        ),
        migrations.AlterModelTable(
            name="sucursal",
            table="sucursal",
        ),
    ]
