# Generated by Django 5.0.6 on 2024-06-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0005_alter_particular_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="particular",
            name="nif",
            field=models.OneToOneField(
                db_column="nif",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="bancaCatalana.client",
            ),
        ),
    ]
