# Generated by Django 5.0.6 on 2024-06-12 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0006_rename_nom_sucursal_nom_ciutat_alter_sucursal_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sucursal",
            name="nom_ciutat",
        ),
    ]
