# Generated by Django 5.0.6 on 2024-06-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancaCatalana', '0006_alter_particular_nif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreccomissions',
            name='idOperacio',
        ),
        migrations.RemoveField(
            model_name='carreccomissions',
            name='import_comissio',
        ),
        migrations.RemoveField(
            model_name='efectiu',
            name='idOperacio',
        ),
        migrations.RemoveField(
            model_name='oficinacentral',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='relaciotransferencies',
            unique_together={('id_operacio1', 'id_operacio2')},
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='IBAN',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='idOperacio',
        ),
        migrations.AddField(
            model_name='carreccomissions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carreccomissions',
            name='id_operacio',
            field=models.OneToOneField(blank=True, db_column='id_operacio', null=True, on_delete=django.db.models.deletion.CASCADE, to='bancaCatalana.operacio'),
        ),
        migrations.AddField(
            model_name='carreccomissions',
            name='import_real',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='id_sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='nif',
            field=models.ForeignKey(db_column='nif', default=1, on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efectiu',
            name='id_operacio',
            field=models.OneToOneField(db_column='id_operacio', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bancaCatalana.operacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacio',
            name='IBAN_origen',
            field=models.ForeignKey(db_column='IBAN_origen', default=1, on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacio',
            name='import_real',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relaciotransferencies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relaciotransferencies',
            name='id_operacio1',
            field=models.ForeignKey(db_column='id_operacio1', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relacio1', to='bancaCatalana.transferencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relaciotransferencies',
            name='id_operacio2',
            field=models.ForeignKey(db_column='id_operacio2', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relacio2', to='bancaCatalana.transferencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nom_ciutat',
            field=models.ForeignKey(db_column='nom_ciutat', default=1, on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.ciutat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='IBAN_desti',
            field=models.ForeignKey(db_column='IBAN_desti', default=1, on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='id_operacio',
            field=models.OneToOneField(db_column='id_operacio', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bancaCatalana.operacio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='import_real',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='efectiu',
            name='quantitat',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nif',
            field=models.OneToOneField(db_column='nif', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bancaCatalana.client'),
        ),
        migrations.AlterField(
            model_name='oficinacentral',
            name='id_oficina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relaciotransferencies',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_empleat',
            field=models.OneToOneField(db_column='id_empleat', on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.gestor'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_oficina',
            field=models.ForeignKey(db_column='id_oficina', on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.oficinacentral'),
        ),
        migrations.AlterModelTable(
            name='carreccomissions',
            table='carrec_comissions',
        ),
        migrations.AlterModelTable(
            name='efectiu',
            table='efectiu',
        ),
        migrations.AlterModelTable(
            name='relaciotransferencies',
            table='relacio_transferencies',
        ),
        migrations.AlterModelTable(
            name='transferencia',
            table='transferencia',
        ),
        migrations.RemoveField(
            model_name='relaciotransferencies',
            name='IBAN',
        ),
        migrations.RemoveField(
            model_name='relaciotransferencies',
            name='idOperacio',
        ),
    ]
