# Generated by Django 5.0.6 on 2024-06-12 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0007_remove_sucursal_nom_ciutat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sucursal",
            name="id_empleat",
        ),
        migrations.RemoveField(
            model_name="sucursal",
            name="id_oficina",
        ),
    ]
