# Generated by Django 5.0.6 on 2024-06-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancaCatalana', '0007_remove_carreccomissions_idoperacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.RESTRICT, to='bancaCatalana.sucursal'),
        ),
    ]
