# Generated by Django 5.0.6 on 2024-06-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancaCatalana', '0008_alter_client_id_sucursal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
