# Generated by Django 5.0.6 on 2024-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancaCatalana', '0009_alter_empresa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinacentral',
            name='id_oficina',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
