# Generated by Django 5.0.6 on 2024-06-12 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bancaCatalana", "0010_rename_entitat_compte_entidad_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operacio",
            old_name="idOperacio",
            new_name="id_operacio",
        ),
        migrations.RemoveField(
            model_name="operacio",
            name="IBAN_origen",
        ),
        migrations.AlterModelTable(
            name="operacio",
            table="operacio",
        ),
    ]
