# Generated by Django 5.0.6 on 2024-06-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancaCatalana', '0011_remove_carreccomissions_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarrecComissions',
        ),
    ]
